void setup_clock();
void save_to_rtc();
void load_from_rtc();
uint_fast8_t get_month();
void set_month(uint_fast8_t month);
uint_fast8_t get_date();
void set_date(uint_fast8_t date);
uint_fast16_t get_year();
void set_year(uint_fast8_t year);
uint_fast8_t get_hours();
void set_hours(uint_fast8_t hours);
uint_fast8_t get_minutes();
void set_minutes(uint_fast8_t minutes);
uint_fast8_t get_seconds();
void set_seconds(uint_fast8_t seconds);
bool is_24_hour();
bool is_pm();
String get_date_string();
String get_time_string();
void set_timezone(String zone);