#pragma once
#include <string>
#include <vector>
#include <map>
#include <Arduino.h>
#include <WiFi.h>
#include <Preferences.h>

#define PREFERENCES_MODE "mode"
#define PREFERENCES_24HOUR "24hour"
#define PREFERENCES_DISPLAY_FORMAT "format"
#define PREFERENCES_LEADING_ZEROS "zeros"
#define PREFERENCES_HOUR_BELLS "bell1"
#define PREFERENCES_HALF_HOUR_BELLS "bell2"
#define PREFERENCES_BRIGHTNESS "brightness"
#define PREFERENCES_BUTTON_BRIGHTNESS "b_brightness"
#define PREFERENCES_EFFECT_BRIGHTNESS "e_bright"
#define PREFERENCES_TIMEZONE "timezone"
#define PREFERENCES_EFFECT_PATTERN "pattern"
#define PREFERENCES_EFFECT_PALETTE "palette"
#define PREFERENCES_BIRTH_MONTH "month"
#define PREFERENCES_BIRTH_DATE "day"
#define PREFERENCES_BIRTH_YEAR "year"
#define PREFERENCES_BIRTH_HOUR "hour"
#define PREFERENCES_BIRTH_MINUTE "minute"
#define PREFERENCES_BIRTH_SECOND "second"

#define DEFAULT_MODE 0
#define DEFAULT_24HOUR 1
#define DEFAULT_DISPLAY_FORMAT 0
#define DEFAULT_LEADING_ZEROS 1
#define DEFAULT_HOUR_BELLS 1
#define DEFAULT_HALF_HOUR_BELLS 1
#define DEFAULT_BRIGHTNESS 15
#define DEFAULT_BUTTON_BRIGHTNESS 25
#define DEFAULT_LED_BRIGHTNESS 25
#define DEFAULT_EFFECT_PATTERN 0
#define DEFAULT_EFFECT_PALETTE 0
#define DEFAULT_TIMEZONE "EST5EDT,M3.2.0,M11.1.0"
#define DEFAULT_BIRTH_MONTH 4
#define DEFAULT_BIRTH_DATE 11
#define DEFAULT_BIRTH_YEAR 1983
#define DEFAULT_BIRTH_HOUR 12
#define DEFAULT_BIRTH_MINUTE 0
#define DEFAULT_BIRTH_SECOND 0

// no magic numbers
#define SECONDS_PER_DAY 86400
#define SECONDS_PER_MINUTE 60
#define SECONDS_PER_HOUR 3600
#define SECONDS_AT_99_HOURS 356400
#define MICROS_PER_SECOND 1000000

extern Preferences preferences;
extern uint_fast32_t timer;
extern bool randomize_effect;

// WiFiUDP ntpUDP;
// NTPClient timeClient(ntpUDP);

enum
{
  CLOCK = 0,
  BIRTHDAY,
  STOPWATCH_PAUSED,
  STOPWATCH_RUNNING,
  TIMER_CHANGE_TIME,
  TIMER_SET_HOURS,
  TIMER_SET_MINUTES,
  TIMER_SET_SECONDS,
  TIMER_PAUSED,
  TIMER_RUNNING,
  CHANGE_MODE,
  SET_MODE,
  CHANGE_DISPLAY_FORMAT,
  SET_DISPLAY_FORMAT,
  CHANGE_24HOUR,
  SET_24HOUR,
  CHANGE_LEADING_ZEROS,
  SET_LEADING_ZEROS,
  CHANGE_HOUR_BELLS,
  SET_HOUR_BELLS,
  CHANGE_HALF_HOUR_BELLS,
  SET_HALF_HOUR_BELLS,
  CHANGE_CLOCK_BRIGHTNESS,
  SET_CLOCK_BRIGHTNESS,
  CHANGE_BUTTON_BRIGHTNESS,
  SET_BUTTON_BRIGHTNESS,
  CHANGE_EFFECT_BRIGHTNESS,
  SET_EFFECT_BRIGHTNESS,
  CHANGE_EFFECT_PATTERN,
  SET_EFFECT_PATTERN,
  CHANGE_EFFECT_PALETTE,
  SET_EFFECT_PALETTE,
  CHANGE_DATE,
  SET_DATE_MONTH,
  SET_DATE_DAY,
  SET_DATE_YEAR,
  CHANGE_TIME,
  SET_TIME_HOURS,
  SET_TIME_MINUTES,
  SET_TIME_SECONDS,
  CHANGE_TARGET_DATE,
  SET_TARGET_MONTH,
  SET_TARGET_DAY,
  SET_TARGET_YEAR,
  CHANGE_TARGET_TIME,
  SET_TARGET_HOURS,
  SET_TARGET_MINUTES,
  SET_TARGET_SECONDS,
  RESET_PREFERENCES,
  CONFIRM_RESET_PREFERENCES,
  LAST_STATE
};

enum
{
  MODE_BIRTHDAY = 0,
  MODE_STOPWATCH,
  MODE_TIMER,
  MODE_CLOCK
};

enum
{
  DISPLAY_AUTO = 0,
  DISPLAY_DATE,
  DISPLAY_TIME,
  DISPLAY_DATE_TIME,
  DISPLAY_TIME_SECONDS
};